DanielPolatajko/inspect_wandb

README.md
inspect_weave/hooks.py
inspect_weave/utils.py
mypy.ini
pyproject.toml
tests/test_utils.py

Utilise wandb init for hook enablement

---

inspect_weave/custom_evaluation_logger.py
inspect_weave/hooks.py
mypy.ini
tests/conftest.py
tests/test_hooks.py

Closes #31, although I believe there's probably much more leverage we can get out of adding more metadata in various places.

Add Inspect metadata to Weave

---

inspect_weave/hooks/model_hooks.py

Add tags for model, dataset and task name to wandb runs, for filtering etc in the UI.

feat(models): add tags to wandb runs

---

.github/workflows/checks.yml
README.md
pyproject.toml
uv.lock

Added a basic workflow for linting and testing. I will make it blocking for PR merge once its working.
Closes #67

chore: add CI checks for linting and testing

---

.vscode/launch.json
inspect_weave/hooks/weave_hooks.py
pyproject.toml
tests/test_weave_hooks.py
uv.lock

Move epoch and sample ID to attributes, since these are metadata fields anyway. No issues with filtering there.
Closes #64 
- [] I have added unit tests to cover any core logic changes

fix(weave): move epoch to attributes

---

inspect_wandb/hooks/weave_hooks.py
tests/test_weave_hooks.py

feat: add sample ID to metadata

---

pyproject.toml
uv.lock

Don't think this is actually a dep, just was for my local testing inspect run

chore: remove datasets dep

---

inspect_wandb/models/hooks.py
tests/conftest.py
tests/test_models/test_hooks.py
tests/test_weave/test_hooks.py

Added some unit tests to cover the existing models hooks logic
Closes #47

test(models): added unit tests for models hooks

---

.vscode/launch.json
pyproject.toml
uv.lock

Relax the constraint on weave version, and install inspect-viz from pypi
Closes #90

chore: relax weave version constraint

---

.github/workflows/publish-to-pypi.yml
.github/workflows/test-build-and-publish.yml
README.md
inspect_wandb/models/hooks.py

chore: fix test pypi build

---

.vscode/launch.json
inspect_wandb/weave/hooks.py
tests/test_weave/test_hooks.py

fix: ensure metadata working well for weave

---

README.md
docs/source/installation.md

fix: update install instructions

---

.github/workflows/publish-to-pypi.yml

fix: use release target for CI releases

---

.github/workflows/publish-to-pypi.yml

* test pypi
* use release target

fix: use release target for CI releases (#125)

---

.github/workflows/publish-to-pypi.yml
inspect_wandb/config/extras_manager.py
pyproject.toml
tests/test_models/test_hooks.py
uv.lock

the viz features are too immature to expose, let's just completely disable them for now. I'll update the docs to remove the references

fix: disable viz

---

.github/pull_request_template.md
CHANGELOG.md

chore: add a changelog

---

CHANGELOG.md
CONTRIBUTING.md
README.md

chore: add contributing.md

---

CHANGELOG.md
CONTRIBUTING.md
README.md

fix: formatting for links to inspect slack

---

.github/workflows/publish-to-pypi.yml

ci: sequence pypi deployments

---

inspect_wandb/models/hooks.py
tests/test_models/test_hooks.py

fix(models): use run id to distinguish runs on eval
